---
title: "Homework 5"
output: github_document
---
```{r setup, include = FALSE}
library(tidyverse)
library(purrr)
library(rvest)
library(dplyr)
library(stringr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## Problem 1

Read in the data.

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unolved",
      disposition == "Closed by arrest"      ~ "solved"
     )
  ) %>% 
  select(city_state, resolved)
```

Let's look at this a bit

```{r}
aggregate_df = 
homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>% 
  broom::tidy()
```

Try to iterate.....
```{r}
results_df = 
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```


```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


## Problem 2

Read and tidy data
```{r}
path_df = 
  tibble(
  path = list.files("lda_data")) %>% 
  mutate(
    path = str_c("lda_data/", path),
    data = map(.x = path, ~ read_csv(.x))) %>% 
  unnest(data) %>% 
  separate(path, into = c("exp_group", "subject_id"), sep = "/") %>% 
  select(-"exp_group") %>% 

  #using str_replace altered the dataframe completely; the only solution is to keep separating out the columns and deleting them. 
  
  separate(subject_id, into = c("exp_id", "throwaway"), sep = ".csv") %>% 
  select(-"throwaway") %>% 
  separate(exp_id, into = c("experiment_group", "subject_id"), sep = "_") %>% 
  mutate(
    experiment_group = recode(experiment_group, con = "control", exp = "experimental")
  ) %>% 
  view()
# you'll want to pivot at some point to format appropriately
# control vs. experimental, week 1-8, which observation 

```



Spaghetti time.
```{r}
path_df %>% 
pivot_longer(week_1:week_8,
               names_to = "week",
               names_prefix = "week_",
               values_to = "observation") 
#%>% 
#   ggplot(aes(x = week, y = observation, group = subject_id, color = subject_id)) +
#  geom_path() +
#  labs(
#    title = "Observations over time",
#    x = "Week",
#    y = "Observation"
#  ) + 
#  viridis::scale_color_viridis(discrete = TRUE) + 
#  theme(legend.position = "bottom")
```

